baseurl      = "localhost"
title        = "El Muso"
languageCode = "en-us"
defaultContentLanguage = "es"
theme        = "hello-friend-ng"
paginate     = 10


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  enableThemeToggle = true
  homeSubtitle = "Aquí encontraras un listado de contenidos digitales (libros) que se producieron a lo largo de mi carrera"
  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false
  # Enable sharing buttons, if you like
  enableSharingButtons = true
  EnableGlobalLanguageMenu = true
  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
  tag      = "tags"
  category = "categories"

[languages]
  [languages.es]
    title = "El Muso - Teoría Musical"
    subtitle = "Preservación y enseñanza musical"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Ver más publicaciones"

    [languages.es.params.logo]
      logoText = "El Muso - Teoría Musical"
      logoHomeLink = "/"

  [languages.en]
    title = "El Muso - Music Theory"
    subtitle = "Musical preservation and teaching"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "El Muso - Music Theory"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
