baseurl      = "localhost"
title        = "El Muso"
languageCode = "en-us"
defaultContentLanguage = "es"

paginate     = 10
collaborators = [
  {name = "Alex", location = "GR", imgurl =""},
  {name = "John", location = "US", imgurl =""}
]

[author]
authors = [
  {name = "El Muso", location = ""}
  # {name = "John", location = "US"}
]


[params]

  customCSS = ["/style.css"]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  enableThemeToggle = true
  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false
  # Enable sharing buttons, if you like
  enableSharingButtons = true
  EnableGlobalLanguageMenu = true
  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
# Disable the default taxonomies
tag = "tags"
category = ""
[languages]
  [languages.es]
  homeSubtitle = "Una serie de contenidos que surgieron por el deseo de tener una distribución justa, y equitativa, de la enseñanza y cultura musical. Gran parte esta hecha en español... por ahora"
    homedownloadprompt = "Para descargar cada contenido, haz click sobre el"
    title = "Otro blog de teoría musical"
    subtitle = "Preservación y enseñanza musical"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Más publicaciones"
    main=[
      {name="Información/Contacto",url="/about"},
      {name="Licencias",url="/licenses"},
      {name="Inicio",url="/"}
      # {name="Colaboradores",url="/helpers"},
    ]
    downloads=[
    {name="El ABC de la teoría musical 1 [PDF]",url="https://github.com/elMuso/ElABCTeoriaMusical/raw/main/El%20ABC%20de%20la%20Teor%C3%ADa%20musical%201.pdf"},
    {name="El ABC de la teoría musical 2 [PDF]",url="https://github.com/elMuso/ElABCTeoriaMusical/raw/main/El%20ABC%20de%20la%20Teor%C3%ADa%20Musical%202.pdf"},
    {name="Ejercicios de teoría musical [PDF]",url="https://github.com/elMuso/ElABCTeoriaMusical/raw/main/CUADERNO%20DE%20EJERCICIOS.pdf"},
    {name="De Obras Bolivianas [PDF]",url="https://github.com/elMuso/DeObrasBolivianas/raw/main/De%20Obras%20Bolivianas.pdf"},
    ]
    [languages.es.params.logo]
      logoText = "ElMuso.github.io"
      logoHomeLink = "/"

  [languages.en]
  homeSubtitle = "A group of content that was made by the desire of having a fair and equal distribution of musical knowledge and cuture. Some of it is only in spanish... for now"
    homedownloadprompt = "To download the content, just click it"
    title = "Another music theory blog"
    subtitle = "Musical preservation and teaching"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Other posts"
    main=[
      {name="About us/Contact",url="/about"},
      {name="Licences",url="/licenses"},
      {name="Home",url="/"}
      # {name="Collaborators",url="/helpers"},
    ]
    downloads=[
    {name="El ABC de la teoría musical 1 [PDF][ES]",url="https://github.com/elMuso/ElABCTeoriaMusical/raw/main/El%20ABC%20de%20la%20Teor%C3%ADa%20musical%201.pdf"},
    {name="El ABC de la teoría musical 2 [PDF][ES]",url="https://github.com/elMuso/ElABCTeoriaMusical/raw/main/El%20ABC%20de%20la%20Teor%C3%ADa%20Musical%202.pdf"},
    {name="Music theory exercises [PDF][ES]",url="https://github.com/elMuso/ElABCTeoriaMusical/raw/main/CUADERNO%20DE%20EJERCICIOS.pdf"},
    {name="De Obras Bolivianas [PDF]",url="https://github.com/elMuso/DeObrasBolivianas/raw/main/De%20Obras%20Bolivianas.pdf"},
    ]
    [languages.en.params.logo]
      logoText = "ElMuso.github.io"
      logoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "tags/"